---
title: "p8105_hw4_yl4923 flexdashboard "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")
rest_inspec = 
  rest_inspec %>%
  select(boro, building, critical_flag, cuisine_description, score, zipcode, grade) %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>%
  mutate(
    boro = str_to_title(boro),
    cuisine_description = replace(cuisine_description, cuisine_description == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)", "Latin"))

common_cuisine = 
  rest_inspec %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(10) %>% 
  select(cuisine_description) %>% 
  inner_join(rest_inspec, ., by = "cuisine_description")
```

## 1 Top 10 Restaurant Cuisine Type Distribution in NYC
```{r}
common_cuisine %>%
  mutate(
    borough = fct_infreq(boro),
    cuisine_description = fct_infreq(cuisine_description)) %>% 
  group_by(borough, cuisine_description) %>% 
  summarise(n = n()) %>%
  plot_ly(x = ~borough, y = ~n, color = ~cuisine_description, type = "bar") %>% 
  layout(yaxis = list(title = 'restaurant number'), barmode = 'stack')
```
